### ISSUE TITLE
[Enhancement] Forge 1.16.5?

### ISSUE THREAD

**Issue by Yurinann** [NoahvdAa/NoChatLag#1]
As the title says, I think 1.16.5 also needs the help of this mod. Much appreciated!

**Comment by Yurinann** [comment]
Wrong repo, sorry

**Comment by NoahvdAa** [comment]
Added in be5be67. You can download the 1.16 version from [Github Releases](https://github.com/NoahvdAa/NoChatLag/releases/tag/1.1.0) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/nochatlag/files/3620252).
